const rowData = [
    {
        Number: "1",
        Type: "Fature Shitje nr-1",
        Client: "Aler-Sherbime Implemetimi",
        Description: "Krijimi i nje layout Ag-Grid",
        Rate: "1",
        Id: Math.floor(Math.random() * 1000),
        Date: "7/12/2022",
        Amount: "12222",
    },
    {
        Number: "2",
        Type: "Fature Shitje nr-2",
        Client: "Aler-Sherbime Implemetimi",
        Description: "Krijimi i nje layout Ag-Grid1",
        Rate: "1",
        Id: Math.floor(Math.random() * 1000),
        Date: "7/12/2022",
        Amount: "13000",
    },
    {
        Number: "3",
        Type: "Fature Shitje nr-3",
        Client: "Aler-Sherbime Implemetimi",
        Description: "Krijimi i nje layout Ag-Grid1",
        Rate: "1",
        Id: Math.floor(Math.random() * 1000),
        Date: "7/12/2022",
        Amount: "130000",
    },
    {
        Number: "4",
        Type: "Fature Shitje nr-4",
        Client: "Aler-Sherbime Implemetimi",
        Description: "Krijimi i nje layout Ag-Grid1",
        Rate: "1",
        Id: Math.floor(Math.random() * 1000),
        Date: "7/12/2022",
        Amount: "130000",
    },
    {
        Number: "5",
        Type: "Fature Shitje nr-5",
        Client: "Aler-Sherbime Implemetimi",
        Description: "Krijimi i nje layout Ag-Grid1",
        Rate: "1",
        Id: Math.floor(Math.random() * 1000),
        Date: "7/12/2022",
        Amount: "130000",
    },
    {
        Number: "6",
        Type: "Fature Shitje nr-6",
        Client: "Aler-Sherbime Implemetimi",
        Description: "Krijimi i nje layout Ag-Grid1",
        Rate: "1",
        Id: Math.floor(Math.random() * 1000),
        Date: "7/12/2022",
        Amount: "130000",
    },
    {
        Number: "7",
        Type: "Fature Shitje nr-7",
        Client: "Aler-Sherbime Implemetimi",
        Description: "Krijimi i nje layout Ag-Grid1",
        Rate: "1",
        Id: Math.floor(Math.random() * 1000),
        Date: "7/12/2022",
        Amount: "130000",
    },
    {
        Number: "8",
        Type: "Fature Shitje nr-8",
        Client: "Aler-Sherbime Implemetimi",
        Description: "Krijimi i nje layout Ag-Grid1",
        Rate: "1",
        Id: Math.floor(Math.random() * 1000),
        Date: "7/12/2022",
        Amount: "130000",
    },
    {
        Number: "",
        Type: "",
        Client: "",
        Description: "",
        Rate: "",
        Id: Math.floor(Math.random() * 1000),
        Date: "",
        Amount: '',
    },
];

export default rowData;